export const JWT_TOKEN = 'signpod-token'
export const TEXT_PRIMARY = 'textPrimary'
export const TEXT_SECONDARY = 'textSecondary'
export const NORMAL = 'normal'
export const OUTLINED = 'outlined'
export const displayFlex = { display: 'flex' }
export const PRIMARY = 'primary'
export const LARGE = 'large'
export const CONTAINED = 'contained'
